---
- name: Install AWX to Kubernetes Cluster
  hosts: localhost
  vars:
    awx_name: awx
    awx_image: quay.io/ansible/awx
    awx_image_tag: devel
    awx_operator_image: quay.io/ansible/awx-operator
    awx_operator_iamge_tag: "1.2.0"
    awx_namespace: awx
    awx_hostname: "{{ awx_name }}.{{ dns_domain }}"
    dns_domain: "{{ ansible_facts['nodename'] }}"
#
  tasks:  
#
  - name: Import install-awx role     
    ansible.builtin.import_role:
      name: install-awx
