---
- name: Ensure pip is installed and upgraded
  ansible.builtin.shell:
    cmd: "{{ ansible_facts.python.executable }} -m ensurepip --upgrade"

- name: Install python kubernetes plugin (required by kubernetes.core collection)
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - oauthlib>=3.2.0
    - kubernetes
