---
- name: Create Artifacts Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - artifacts
    - artifacts/{{ awx_hostname }}
    - artifacts/{{ awx_hostname }}/kustomization

- name: Create manifests from templates
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: artifacts/{{ awx_hostname }}/{{ item }}
  loop:
    - awx.yaml
    - kustomization/kustomization.yaml

- name: Create Operator Deployment from kustomization
  kubernetes.core.k8s:     
    state: present
    definition:  "{{ lookup('kubernetes.core.kustomize', dir='artifacts/'+awx_hostname+'/kustomization') }}"
    wait: yes

- name: Create AWX - {{ awx_hostname }}
  kubernetes.core.k8s:
    state: present
    src: artifacts/{{ awx_hostname }}/awx.yaml
    wait: yes
    wait_condition:
      type: Running
      status: "True"
